server:
    port: 18081

spring:
    application:
        name: luckycat
    datasource:
        url: jdbc:mysql://localhost:31306/luckycat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
        username: luckycat
        password: luckycat
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    jackson:
        serialization:
            fail-on-empty-beans: false
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8


dify:
    apiKey: "app-"
    url: "https://api.dify.ai/v1"